#737 update Netty to 4.1.59.Final
diennea/herddb pull request #738
Opened 2021-02-23 11:30 UTC by dmercuriali

Updated Netty4 dependency to 4.1.59.Final

 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

2021-02-23 11:59 UTC, eolivelli requested changes

2021-02-23 11:59 UTC, eolivelli commented on pom.xml
>          <libs.netty4ssl>2.0.28.Final</libs.netty4ssl>
you have to update this version as well with the latest supported version

2021-02-23 14:02 UTC, eolivelli approved these changes
LGTM

2021-02-26 14:04 UTC, dmercuriali commented
rebased on master

2021-03-02 06:15 UTC, merged